import { ExternalLinkIcon } from '@chakra-ui/icons';
import { Link } from '@chakra-ui/react';
import Head from 'next/head';

import type { NextPage } from 'next';

import Synth from '@/components/synth';
import { SynthProvider } from "@/providers/synth"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Web Synth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Heading>第1回 ブラウザでシンセサイザーを作る会</Heading> */}
        <SynthProvider>
          <Synth />
        </SynthProvider>
      </main>

      <footer>
        <Link href="https://twitter.com/m1m0zzz" isExternal>
          Powered by @m1m0zzz <ExternalLinkIcon mx='2px' />
        </Link>
      </footer>
    </div>
  );
};

export default Home;
