import type { NextPage } from 'next'
import Head from 'next/head'
import { Heading } from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import Synth from '@/components/synth'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Web Synth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>第1回 ブラウザでシンセサイザーを作る会</Heading>
        <Synth />
      </main>

      <footer>
        <a href="https://twitter.com/m1m0zzz" target="_blank" rel="noopener noreferrer">
          Powered by @m1m0zzz <ExternalLinkIcon mx='2px' />
        </a>
      </footer>
    </div>
  )
}

export default Home
